version: '3.8'


services:

  asterisk:
    build: 
      context: ./docker-asterisk/
      dockerfile: dockerfile
    container_name: asterisk
    ports:
      - 5060:5060
    networks:
      - compose-bridge

  python:
    build: 
      context: ./docker-python/
      dockerfile: dockerfile
    container_name: python
    networks:
      - compose-bridge

networks:
  compose-bridge:
    driver: bridge