version: '3.8'


services:

  asterisk:
    build: 
      context: ./docker-asterisk/
      dockerfile: dockerfile
    container_name: asterisk
    ports:
      - 8088:8088
      - "5060:5060/udp"
      - "10000:10010/udp"
    volumes:
      - ./docker-asterisk/asterisk.conf:/etc/asterisk/asterisk.conf
      - ./docker-asterisk/extensions.conf:/etc/asterisk/extensions.conf
      - ./docker-asterisk/pjsip.conf:/etc/asterisk/pjsip.conf
    networks:
      - compose-bridge

  python:
    build: 
      context: ./docker-python/
      dockerfile: dockerfile
    container_name: python
    networks:
      - compose-bridge
    depends_on:
      - asterisk

networks:
  compose-bridge:
    driver: bridge
