version: '3.8'


services:

  asterisk:
    build: 
      context: ./docker-asterisk/
      dockerfile: dockerfile
    container_name: asterisk
    restart: always
    entrypoint: asterisk -cfgvvvv
    env_file: .env
    ports:
      - 8088:8088
      - "5060:5060/udp"
      - "10000-10100:10000-10100/udp"
    volumes:
      - ./docker-asterisk/asterisk/asterisk.conf:/etc/asterisk/asterisk.conf
      - ./docker-asterisk/asterisk/extensions.conf:/etc/asterisk/extensions.conf
      - ./docker-asterisk/asterisk/pjsip.conf:/etc/asterisk/pjsip.conf
      - ./docker-asterisk/asterisk/ari.conf:/etc/asterisk/ari.conf
      - ./docker-asterisk/asterisk/http.conf:/etc/asterisk/http.conf
    networks:
      - compose-bridge


  python:
    build: 
      context: ./docker-python/
      dockerfile: dockerfile
    volumes:
      - ./docker-python/ura.py:/py/ura.py
    container_name: python    
    restart: always
    env_file: .env
    networks:
      - compose-bridge

networks:
  compose-bridge:
    driver: bridge

