# Use a CentOS 7 base image
FROM centos:7
WORKDIR /
LABEL maintainer="Fortics"

COPY convert.sh /var/tmp/

RUN yum -y update && \
    yum -y install epel-release && \
    yum -y install wget gcc ncurses-devel libxml2-devel sqlite-devel jansson-devel uuid-devel openssl-devel libedit-devel libsrtp-devel speex-devel pjproject-devel make unzip sox whois dos2unix && \    
    # Baixando e descompactando e instalando asterisk
    mkdir -p /usr/src && \
    cd /usr/src && \
    wget https://downloads.asterisk.org/pub/telephony/asterisk/releases/asterisk-18.11.2.tar.gz && \
    tar -zxvf asterisk-18.11.2.tar.gz && \
    bash /usr/src/asterisk-18.11.2/contrib/scripts/install_prereq install && \
    cd /usr/src/asterisk-18.11.2 && \
    ./configure --with-jansson-bundled && \
    make && \
    make install && \
    make samples && \
    make config && \
    yum clean all && \
    rm -rf /usr/src/asterisk-* && \
    rm -f /usr/src/asterisk-18-current.tar.gz && \      
    #Configuração de audios em pt-br
    mkdir /var/lib/asterisk/sounds/pt-br && \
    cd /var/lib/asterisk/sounds/pt-br && \
    wget -O core.zip https://www.asterisksounds.org:443/pt-br/download/asterisk-sounds-core-pt-BR-sln16.zip && \
    wget -O extra.zip https://www.asterisksounds.org:443/pt-br/download/asterisk-sounds-extra-pt-BR-sln16.zip && \
    unzip -o core.zip && \
    unzip -o extra.zip && \
    cp /var/tmp/convert.sh /var/lib/asterisk/sounds/pt-br/ && \     
    bash /var/lib/asterisk/sounds/pt-br/convert.sh && \
    chmod +x /var/lib/asterisk/sounds/pt-br/*

