# Use a CentOS 7 base image
FROM centos:7
WORKDIR /
LABEL maintainer="Fortics"
RUN yum -y update && \
    yum -y install epel-release && \
    yum -y install wget gcc ncurses-devel libxml2-devel sqlite-devel jansson-devel uuid-devel openssl-devel libedit-devel libsrtp-devel speex-devel pjproject-devel make

# Baixando e descompactando e instalando asterisk
RUN mkdir -p /usr/src && \
    cd /usr/src && \
    wget https://downloads.asterisk.org/pub/telephony/asterisk/releases/asterisk-18.11.2.tar.gz && \
    tar -zxvf asterisk-18.11.2.tar.gz

RUN bash /usr/src/asterisk-18.11.2/contrib/scripts/install_prereq install && \
    cd /usr/src/asterisk-18.11.2 && \
    ./configure --with-jansson-bundled && \
    make && \
    make install && \
    make samples && \
    make config

RUN yum clean all && \
    rm -rf /usr/src/asterisk-* && \
    rm -f /usr/src/asterisk-18-current.tar.gz

# Configurando ARI no asterisk
RUN yum install npm -y && \
    npm install -g wscat && \
    yum install curl -y && \
    echo -e "[general]\nenabled = yes\nbindaddr = 0.0.0.0" > /etc/asterisk/http.conf && \
    echo -e "[general]\nenabled = yes\npretty = yes\nallowed_origins =\n\n[asterisk]\ntype = user\nread_only = no\npassword = asterisk" > /etc/asterisk/ari.conf

#Instalando requerimentos
RUN yum install vim -y && \
    yum install whois -y

#Configuração de audios em pt-br
RUN mkdir /var/lib/asterisk/sounds/pt-br && \
    cd /var/lib/asterisk/sounds/pt-br && \
    wget -O core.zip https://www.asterisksounds.org:443/pt-br/download/asterisk-sounds-core-pt-BR-sln16.zip && \
    wget -O extra.zip https://www.asterisksounds.org:443/pt-br/download/asterisk-sounds-extra-pt-BR-sln16.zip && \
    yum install unzip -y && \
    unzip -o core.zip && \
    unzip -o extra.zip && \
    yum install sox -y 
COPY convert.sh /var/lib/asterisk/sounds/pt-br/
RUN cd /var/lib/asterisk/sounds/pt-br && \
    bash convert.sh && \
    chmod +x * 

CMD /etc/init.d/asterisk start && tail -f /dev/null

